services:

  kafka:
    container_name: kafka
    image: bitnamilegacy/kafka:latest
    ports:
      - "9092:9092"
    env_file:
      .env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 30

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP-интерфейс
      - "9000:9000"   # TCP-интерфейс для клиентов
    env_file:
      .env
    ulimits:
      nofile:
        soft: 262144 #текущий лимит
        hard: 262144 # потолок
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init-scripts:/docker-entrypoint-initdb.d  # Добавляем путь к скриптам
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: [ "python", "-m", "consumer.consumer" ]
    volumes:
      - .:/app
      - rocksdb_data:/var/lib/rocksdb
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  clickhouse_data:
  rocksdb_data:
